name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip wget openjdk-17-jdk libncurses5-dev

      - name: Install Android Command-line Tools & Accept Licenses
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          unzip tools.zip -d tmp
          mkdir -p latest
          mv tmp/cmdline-tools/* latest/
          rm -rf tmp tools.zip
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          mkdir -p $ANDROID_HOME/licenses
          echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_HOME/licenses/android-sdk-license
          echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" >> $ANDROID_HOME/licenses/android-sdk-license
          yes | sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "build-tools;36.0.0" "platforms;android-33" "ndk;25.2.9519653"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Cache Buildozer .buildozer folder
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-${{ runner.os }}-

      - name: Build APK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          set -e
          buildozer -v android debug
          echo ">>> Listing all generated APK files:"
          find . -name "*.apk" || echo "No APK found"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FlappyBird-APK
          path: |
            bin/*.apk
            .buildozer/android/platform/build-*/android/bin/*.apk
